- src/css/custom.css
Updating css colors to use the datafold blue.
> Update primary and highlight colors

- docs/guides/ci_guides_overview.md
This is an attempt to give a quick overview and definition of CI that will precede the more detailed guides.
> [PX-175] CI overview

- docs/overview.md
> [PX-219] Why Datafold 

- docs/overview.mdx
- package.json
add react-player so the video in overview will play
> add react-player

- docs/os_diff/about.md
- docs/os_diff/how_to_implement_new_database_driver.md
- docs/os_diff/python_api.md
Adding information that was previously only in the [readthedocs](https://data-diff.readthedocs.io/en/latest/).
- new database driver
- Python API info
- anything else that I notice
> add how to implement a new database driver and python api reference

- docs/os_diff/how_to_implement_new_database_driver.md
I improved the docs in the data-diff repo.  
Erez suggested we move the changes here.
> Updated the DB driver creation docs

- docs/guides/ci_guides/dbt_core/circleci.md
- docs/guides/ci_guides/dbt_core/github_actions.md
- docs/guides/ci_guides/dbt_core/gitlab_ci.md
Datafold steps not being in "basic" configs has caused confusion around whether slim ci is required to use Datafold.
> include datafold steps in "basic" configs

- docs/guides/ci_guides/slim_ci.md
- docs/integrations/orchestration/datafold-sdk.md
- docs/integrations/orchestration/slim_ci.md
Documentation of our Slim CI feature which is now available to all customers.
- Page in the documentation with screenshots
- Loom video
> Add slim ci guide

- docs/guides/os_diff.md
- docs/os_diff/about.md
- docs/os_diff/how_to_install.md
- docs/os_diff/how_to_use/how_to_use_with_command_line.md
Remove pre-release flags corresponding to open source 0.3 release and promotion.
> remove pre-release flags

- README.md
Rephrased + made it slightly easier to follow.
> Standardized the commands in the readme

- docs/guides/ci_guides/dbt_core/github_actions.md
Adding documentation on how to skip GHA workflows for draft PRs.
> [PX-336] skip diffs for draft pull requests

- docs/guides/ci_guides/slim_diff.md
Per Gleb's request. https://datafold.slack.com/archives/C04HFLT3BNG/p1675285472510549?thread_ts=1675283486.586599&cid=C04HFLT3BNG
> change wording of slim diff guide

- docs/guides/ci_guides/dbt_core/github_actions.md
Seems like a todo bullet slipped through, I don't think this section is necessary.
> removing a todo

- docs/deployment_testing.md
Add links to the following sections:
- Data Source
- Source Control
- dbt Core/Cloud
- Data Apps
> Add links to Deployment Testing Getting Started

- docs/development_testing/open_source.md
Add configuration details for the change here https://github.com/datafold/data-diff/pull/498
> add detail on custom schemas config

- docs/development_testing/open_source.md
Adds this:
Links to https://github.com/datafold/data-diff/releases
> Remind folks to update

- docs/guides/ci/gitlab_ci.md
Improving the GitLab + dbt Core guide, and add guidelines for using dedicated PR database instead of PR schema.
> use <> for variables names instead of placeholder strings; support MR database

- docs/deployment_testing/source_control/GitLab.md
Move the access requirements before screenshot.
Addresses feedback in https://github.com/datafold/datafold-docs/pull/156.
> Reorder GitLab docs

- docs/deployment_testing/dbt/dbt_cloud.md
- docs/deployment_testing/dbt/dbt_core.md
Addresses the main issues with the dbt Core and Cloud docs in https://github.com/datafold/datafold-docs/pull/156
> Iterate on dbt docs

- docs/development_testing/open_source.md
Oops, forgot a word ("to"). Also added the word `dbt`.
> add the word 'to'

- docs/deployment_testing/dbt.md
Broken links in `deployment_testing/dbt.md`.
> fix links in deployment_testing/dbt.md

- docs/getting_started.md
Adding the gif to the homepage for increased magic. 🪄
> add gif to homepage

- docs/deployment_testing.md
- docs/development_testing/cloud.md
- docs/development_testing/open_source.md
Gleb had some good feedback about how the current pages framing dev vs deployment testing, namely that they lacked important CTAs (for users who are interested in CI) and clarifications about what you get out of each part of the tool.
As always, this is iterative, but I thought there were some quick wins that should not wait seeing as we have just sent a ton of outbound.
Summary of changes:
- Add CTA for anyone interested in CI.
- Align text describing deployment and development testing with text currently on datafold.com.
- Remove the table of contents sidebar for these pages. Rationale: 
- the pages are pretty short, so the ToC doesn't add much
- the ToCs were automatically including header text that wasn't appropriate for a ToC.
- So, I thought it was better just to remove it, and not …
> Organize docs around intended onboarding experience to dev + deploy testing

- docs/development_testing/open_source.md
> spell developmnt correctly

- docs/development_testing/open_source.md
I created a section at the bottom of the installation page, "Optional configurations and flags", where we can add features, functionalities, flags, configs as we address more use cases to drive adoption.
In addition to creating the section, I added the following subsections:
- How to handle large models
- How to use `--select`
> clarify how to handle large models and add docs for `--dbt --select`

- docs/development_testing/open_source.md
Adding a clarification here now that custom databases are supported
> clarify that prod_database is the default

- docs/development_testing/open_source.md
Good catch from @cfernhout 
Was released in [v0.7.5](https://github.com/datafold/data-diff/releases/tag/v0.7.5)
> --select version

- docs/development_testing/cloud.md
Update the docs to reflect Team Cloud as the available option for diffing in development using the cloud application.
> community cloud --> team cloud

- docs/guides/ci.md
> Update ci.md - typo

- docs/deployment_testing/team_cloud/getting_started_for_customers.md
- docs/deployment_testing/team_cloud/getting_started_for_customers/dbt_in_ci.md
- docs/deployment_testing/team_cloud/how_datafold_team_cloud_works.md
- sidebars.js
Updating the docs to help people get oriented about how dbt and Datafold interact in CI.
> PRO-89 WIP: add dbt in ci page

- docs/guides/ci/github_actions.md
A bit of copy editing and clarification based on feedback I've received from onboarding users.
> tidy up github_actions.md

- docusaurus.config.js
Update redirects per this thread https://datafold.slack.com/archives/C03CS4L7GSK/p1687548769636429
> add to redirects
