- docs/overview.mdx
Keep autoplay on, but mute the video so that you don't hear it start every time you navigate to the overview page
> Mute overview video

- docs/features/alerts.md
- docs/features/catalog-lineage.md
- docs/features/data_diff.md
- docs/overview.mdx
I found the documentation for Lineage lacking--basically, I couldn't find Lineage in the Datafold app. It wasn't obvious to me that you had to go to Catalog and click on a table to see its Lineage.
I've added a few points that I think will help someone with that. 
It's a bit of an awkward fit because the Features pages (lineage, catalog, diff, alerts) are framed more as "here are the great benefits" more than "how-to docs." I think longer term, these features deserve their own explainers in the broader docs section; even though they're (by design) not technically complex to use, the user still needs some basic instructions that don't really belong in the Features page.
But, I think this is worth merging as a quick fix / incremental improvement until we create a more holistic solution.
> spruce up features (lineage, catalog, diff, alerts)

- docs/os_diff/how_to_use.md
I've added more detail to the docs explaining how to use a TOML file. In the future, I'd like to create a Loom, but I think we could consider merging this as an incremental improvement. I'm open to feedback and ideas.
Medium-term, I'd like to restructure this so the TOML config setup and walkthrough is not buried far down the `How to Use` page. However, I'd like to prioritize this update and then separately consider the structure, since I believe users can benefit today from this additional detail about how to use a config file.
> add walkthrough of toml

- docs/os_diff/how_to_use/how_to_use_with_toml.md
Use `python` highlighting because `toml` highlighting doesn't work in docusaurus.
> fix toml highlighting

- docs/integrations/data_warehouses/content/snowflake.md
This section is a bit misleading, and has caused customers to enter the full url
> clarify the value to enter for account

- .github/CODEOWNERS
This PR makes the entire Datafold PX team codeowners of the os_diff section of the repo. This ensures anyone on the team is able to respond to issues such as broken links, typos, etc.
> update codeowners of docs/os_diff

- docs/integrations/orchestration/dbt_cloud.md
Updating the name of prod job to be artifacts job, corresponding to this PR: https://github.com/datafold/datafold/pull/2939
Users have to date been instructed to select the job that creates production tables. This is not actually ideal if they only create production tables every e.g. 24hrs but more frequently push to main.
> change prod job to artifacts job

- docs/os_diff/dbt_integration.md
If data-diff is already installed, the command will not upgrade by default
> add upgrade flag

- docs/os_diff/dbt_integration.md
You don't need to use sqeleton to install database connectors. Instead, you can use data-diff
> switch to data-diff

- docs/integrations/git/github.md
Adding requirements for installing the Datafold GitHub integration
Need to do the same for GitLab, but I'll do that separately
> [PX-389] add githbub app pereqs to docs

- docusaurus.config.js
Per discussion [here](https://datafold.slack.com/archives/C03MWG27G01/p1677091357072649), this renames tabs
* Rename “Docs” tab -> Datafold Cloud
* Rename “Open Source” tab -> “Open Source Data Diff”
To avoid needing to update links, I only changed the label. Assuming we'll continue iterating and this is just a quick win.
We also discussed moving the API and Guides tab, but I'll do that in a separate PR because it's more involved.
Rendered:
<kbd>
</kbd>
> [PX-401] rename docs and open source tabs

- docs/api/content/graphql.md
- docs/integrations/data_warehouses/content/postgres/postgres_aurora.md
- docs/on-prem/content/slack_on-prem.md
- docs/os_diff/how_to_use/how_to_use_with_command_line.md
When adding a link checker to CI, the checker flagged a few missing anchors. This PR fixes four missing anchors.
```
GitHub linkcheck https://docs.datafold.com/
Done crawling.                   
https://docs.datafold.com/api/content/graphql/
- (15:7183) 'GraphQL ..' => https://docs.datafold.com/api/content/graphql#graphql-chema (HTTP 200 but missing anchor)
- redirect path:
- https://docs.datafold.com/api/content/graphql (301)
- /api/content/graphql/ (200)
https://docs.datafold.com/integrations/data_warehouses/content/postgres/postgres_aurora/
- (15:12225) 'Increase..' => https://docs.datafold.com/integrations/data_warehouses/content/postgres/postgres_aurora#increased-verbosity (HTTP 200 but missing anchor)
- redirect path:
- https://docs.datafold.com/integrations/data_warehouses/content/p …
```
> [PX 403] broken anchors

- docs/integrations/orchestration/dbt_adv_config.md
I noticed that the composite key example only has a single key, and thought giving a more explicit example is helpful
I also renamed the example keys from `user_id` and `version_id` to `user_id` and `company_id` - I think that's a more plausible and common example.
**current state**
<kbd>
</kbd>
**proposed**:
<kbd>
</kbd>
> [PX-395] add second key to composite key example

- docs/integrations/orchestration/dbt_cloud/configuration.md
The option was removed from UI because we should always use "merge base" for dbt Cloud configs.
> Removed "base branch selection strategy" from dbt Cloud docs

- docs/development_testing/open_source.md
Update https://docs.datafold.com/development_testing/open_source/ to link to PK guidance in https://docs.datafold.com/guides/dbt_advanced_configs/#tag-primary-keys since there's parity now. (yay!)
> update PK guidance

- docs/development_testing/open_source.md
Some users are missing dependencies for `data-diff --dbt`. Slightly more verbose installation commands prevents this from happening.
> avoid missing dependencies errors

- docs/guides/dbt_advanced_configs.md
This addresses the issue that `dbt_advanced_configs.md` combined the yaml for Timeline and Time Travel under one section (Time Travel) and did not explain Timeline.
> add Timeline to dbt_advanced_configs

- docs/getting_started.md
This PR removes some extra text and aligns the language describing development/deployment testing with the website copy.
I think there's some more stuff we can add to this page, but this edit cleans it up and gives us a good place to iterate from.
> remove text, align language with website copy

- .github/workflows/markdown_link_check.yml
- mlc_config.json
This PR adds checks for broken links in CI. It only checks modified files.
Docusaurus has an [onBrokenLinks](https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks) config, but it is only available for production builds.
There are quite a few tools that check for links on broken sites, and I tried out several different tools in the course of this PR. [Markdown link check](https://github.com/tcort/markdown-link-check) can be run prior to deploy (several tools required a url), and seems to have quite a few config options.
No broken links ✅ 
With broken links ❌ 
Next steps
* This only checks modified files. I think it makes sense to add a job that runs weekly to check the whole site.
* Need to check for existing broken links, and fix as needed.
CI improvements:
* It would be neat if …
> [PX-394] link check in CI

- docs/development_testing/open_source.md
Seems like we're not quite ready for #169 , opening this to remove non-existent dbt extra
> remove data-diff[dbt] extra from install

- docs/deployment_testing.md
- docs/deployment_testing/getting_started_for_customers.md
- sidebars.js
I thought it made sense to have "Team Cloud" in the menu under both Dev and Deployment testing, which makes it clear that you can use Team Cloud in these two contexts. I also separated out the Getting Started for Customers page, which was buried at the bottom of the page formerly known as Getting Started.
> better menu structure consistency between dev and depl testing

- docs/guides/dbt_advanced_configs.md
Caught a syntax error (missing `"`) when working with a customer. 
Also added another date example for the same config.
> fix syntax of filter clause in dbt advanced configs

- docs/enterprise_accounts/catalog-lineage.md
- docs/enterprise_accounts/sso.md
1. Lineage docs links in app currently broken - would like to resurrect a minimal page to help there.
2. Can hide it from public, figured SEO wise it's easier and better to put it in Enterprise features. Lmk if there's a strong reason not to do so.
> Add lineage to enterprise features & for doc reference
